spring:
  profiles:
    active: @profileActive@
    mvc: throw-exception-if-no-handler-found:true
    resources: add-mappings=false
server:
  port: 8091
  servlet:
    context-path: /

mybatis:
  type-aliases-package: modules/entity/**
  mapper-locations: mapper/*.xml

swagger:
    version: 2.8.0