# 日志
logging:
  level:
    root:
    - error
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug
wx:
  pay:
    appId: #微信公众号或者小程序等的appid
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）

# 数据库
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://119.23.187.225:5432/postgres
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  redis:
    host: 119.23.187.225
    database: 0
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1s
        max-idle: 10
        min-idle: 1
    timeout: 1000ms

