server:
  port: 8091

spring:
  profiles:
    active: @spring.profiles.active@
    mvc: throw-exception-if-no-handler-found:true
    resources: add-mappings=false

mybatis:
  type-aliases-package: modules/entity/**
  mapper-locations: mapper/*.xml

swagger:
    version: 2.8.0